In [0]:
import numpy as np
import pandas as pd

In [0]:
data = {
    "BoyOrGirl": [
        "Boy",
        "Boy",
        "Boy",
        "Girl",
        "Boy",
        "Girl",
        "Boy",
        "Boy",
        "Girl",
        "Girl",
        "Boy",
        "Boy",
    ],
    "TestScore": [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70],
    "TestScore1": [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, np.nan, 70],
}

In [62]:
df = pd.DataFrame(data, columns = ['BoyOrGirl', 'TestScore', 'TestScore1'])
df

   BoyOrGirl  TestScore  TestScore1
0        Boy         25        25.0
1        Boy         94        94.0
2        Boy         57        57.0
3       Girl         62        62.0
4        Boy         70        70.0
5       Girl         25        25.0
6        Boy         94        94.0
7        Boy         57        57.0
8       Girl         62        62.0
9       Girl         70        70.0
10       Boy         62         NaN
11       Boy         70        70.0

In [0]:
df.BoyOrGirl.value_counts().shape[0]

2

In [0]:
df.loc[df.loc[:, "BoyOrGirl"] == "Girl"]

  BoyOrGirl  TestScore
3      Girl         62
5      Girl         25
8      Girl         62
9      Girl         70

In [0]:
df.shape

(12, 2)

In [49]:
groupby_gender = df.groupby(df['BoyOrGirl'])
groupby_gender

In [50]:
for g in groupby_gender:
    print(g)

('Boy',    BoyOrGirl  TestScore  TestScore1
0        Boy         25          25
1        Boy         94          94
2        Boy         57          57
4        Boy         70          70
6        Boy         94          94
7        Boy         57          57
10       Boy         62          62
11       Boy         70          70)
('Girl',   BoyOrGirl  TestScore  TestScore1
3      Girl         62          62
5      Girl         25          25
8      Girl         62          62
9      Girl         70          70)

In [0]:
len(list(df['TestScore'].groupby(df['BoyOrGirl'])))

2

In [0]:
range_values = lambda x : x.max() - x.min()

In [51]:
df.groupby(["BoyOrGirl"]).agg(
    {"TestScore": ["sum", "max", "min", "mean", ('other', lambda x: x.max() - x.min())],
     "TestScore1": ["sum",]}
)

          TestScore                       TestScore1
                sum max min    mean other        sum
BoyOrGirl
Boy             529  94  25  66.125    69        529
Girl            219  70  25  54.750    45        219

In [0]:
list(df['TestScore'].groupby(df['BoyOrGirl']))[1]

('Girl', 3    62
 5    25
 8    62
 9    70
 Name: TestScore, dtype: int64)

In [0]:
df.groupby(df['BoyOrGirl']).agg({"TestScore" : "max"})

           TestScore
BoyOrGirl
Boy               94
Girl              70

In [57]:
df

   BoyOrGirl  TestScore  TestScore1
0        Boy         25          25
1        Boy         94          94
2        Boy         57          57
3       Girl         62          62
4        Boy         70          70
5       Girl         25          25
6        Boy         94          94
7        Boy         57          57
8       Girl         62          62
9       Girl         70          70
10       Boy         62          62
11       Boy         70          70

In [63]:
df.TestScore.count()

12

In [64]:
df.TestScore1.count()

11

In [65]:
df["BoyOrGirl"].value_counts()

Boy     8
Girl    4
Name: BoyOrGirl, dtype: int64

In [66]:
df["BoyOrGirl"].unique()

array(['Boy', 'Girl'], dtype=object)

In [67]:
df["BoyOrGirl"].nunique()

2

In [77]:
df["BoyOrGirl"].value_counts().index

Index(['Boy', 'Girl'], dtype='object')

In [0]:
list(df['TestScore'].groupby(df['BoyOrGirl']))[0][1].max()

94

In [0]:
list(df['TestScore'].groupby(df['BoyOrGirl']))[1][1].max()

70

In [0]:
df.groupby(["BoyOrGirl"]).agg(
    {"TestScore": ["sum", "max", "min", "mean", ('other', lambda x: x.max() - x.min())]}
)

          TestScore
                sum max min    mean other
BoyOrGirl
Boy             529  94  25  66.125    69
Girl            219  70  25  54.750    45

In [0]:
list(df['TestScore'].groupby(df['BoyOrGirl']))

In [0]:
list(df['TestScore'].groupby(df['BoyOrGirl']))[0]

In [0]:
len(list(df['TestScore'].groupby(df['BoyOrGirl']))[0])

In [0]:
list(df['TestScore'].groupby(df['BoyOrGirl']))[0][1]

In [0]:
sum(list(df['TestScore'].groupby(df['BoyOrGirl']))[0][1])

In [0]:
max(list(df['TestScore'].groupby(df['BoyOrGirl']))[0][1])

In [0]:
np.average(list(df['TestScore'].groupby(df['BoyOrGirl']))[0][1])

In [0]:
data = {
    "BoyOrGirl": [
        "Boy",
        "Boy",
        "Boy",
        "Girl",
        "Boy",
        "Girl",
        "Boy",
        "Boy",
        "Girl",
        "Girl",
        "Boy",
        "Boy",
    ],
    "Gender": ["M", "F", "M", "M", "F", "F", "F", "M","F", "F", "F", "M"],
    "TestScore": [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70],
}

In [0]:
df = pd.DataFrame(data, columns = ['BoyOrGirl', 'TestScore', "Gender" ])

In [89]:
df

   BoyOrGirl  TestScore Gender
0        Boy         25      M
1        Boy         94      F
2        Boy         57      M
3       Girl         62      M
4        Boy         70      F
5       Girl         25      F
6        Boy         94      F
7        Boy         57      M
8       Girl         62      F
9       Girl         70      F
10       Boy         62      F
11       Boy         70      M

In [92]:
pd.pivot_table(df, index=["BoyOrGirl"], columns=["Gender"], values="TestScore")

Gender             F      M
BoyOrGirl
Boy        80.000000  52.25
Girl       52.333333  62.00

In [83]:
pd.pivot_table(df, index=["BoyOrGirl"], values="TestScore",
               aggfunc= [np.mean, np.median, min, max, np.std])

               mean    median       min       max        std
          TestScore TestScore TestScore TestScore  TestScore
BoyOrGirl
Boy          66.125        66        25        94  22.228923
Girl         54.750        62        25        70  20.188693

In [93]:
pd.pivot_table(df, index=["BoyOrGirl"], values="TestScore",
               aggfunc= ["count"])

              count
          TestScore
BoyOrGirl
Boy               8
Girl              4